import React from 'react';
import {
    CircularLoader,
    NoticeBox,
} from '@dhis2/ui';
import { Card } from '@dhis2-chap/ui';
import i18n from '@dhis2/d2-i18n';
import styles from './PredictionsNewPage.module.css';
import { usePredictions } from '../../hooks/usePredictions';
import { PredictionsTable } from '../../components/PredictionsTable';
import { PageHeader } from '../../features/common-features/PageHeader/PageHeader';

export const PredictionsNewPage: React.FC = () => {
    const { predictions, error: predictionsError, isLoading: predictionsLoading } = usePredictions();

    if (predictionsLoading) {
        return (
            <div className={styles.loadingContainer}>
                <CircularLoader />
            </div>
        );
    }

    if (predictionsError) {
        return (
            <div className={styles.errorContainer}>
                <NoticeBox error title={i18n.t('Error loading predictions') as string}>
                    {predictionsError?.message || (i18n.t('An unknown error occurred') as string)}
                </NoticeBox>
            </div>
        );
    }

    return (
        <>
            <PageHeader
                pageTitle={i18n.t('Predictions (New)')}
                pageDescription={i18n.t('Forecasted disease trends generated by applying a predictive model to current data. These can be reviewed and imported into DHIS2 to support decision-making in the field.')}
            />
            <Card className={styles.container}>
                <PredictionsTable predictions={predictions || []} />
            </Card>
        </>
    );
};
